# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: "./_webui/package-lock.json"

      - run: npm ci
        working-directory: ./_webui
      - run: npm run build
        working-directory: ./_webui

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build Go
        run: go build -v ./...

      - name: Test Go
        run: go test -v ./...

      - name: Build demo command
        run: CGO_ENABLED=0 go build -v
        working-directory: ./cmd/demo

      - name: Upload demo command
        uses: actions/upload-artifact@v3
        with:
          name: demo
          path: cmd/demo/demo

      - name: Build aws lambda handler
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -tags lambda.norpc -o bootstrap main.go
        working-directory: ./cmd/demo-aws-lambda

      - name: Upload aws lambda handler
        uses: actions/upload-artifact@v3
        with:
          name: demo-aws-lambda
          path: cmd/demo-aws-lambda/bootstrap
