name: Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: "./_webui/package-lock.json"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Prepare build environment
        run: |
          echo Running on $BRANCH_NAME
          mkdir build-results
          wget -q https://github.com/Zxilly/go-size-analyzer/releases/download/v0.2.4/go-size-analyzer_linux_amd64.tar.gz -O gsa.tar.gz 
          tar -xzf gsa.tar.gz gsa
          chmod +x gsa
          go install github.com/medyagh/gopogh/cmd/gopogh@latest
          go install github.com/nikolaydubina/go-cover-treemap@latest
          go install github.com/mfridman/tparse@latest
        working-directory: /tmp
          

      - run: npm ci
        working-directory: ./_webui
      - run: npm run build
        working-directory: ./_webui

      - name: Dump Go env
        run: go env

      - name: Build Go
        run: go build -v ./...

      - name: Test Go
        env:
          TIDB_PASSWORD: ${{ secrets.TIDB_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-central-1"
        run: |
          go test ./... -coverprofile /tmp/build-results/cover.out -json > /tmp/build-results/test-report.json
          tparse -all -file=/tmp/build-results/test-report.json

      - name: Save test results
        if: success() || failure()
        run: |
          go tool cover -html=/tmp/build-results/cover.out -o /tmp/build-results/cover.html
          gopogh -in /tmp/build-results/test-report.json -out_html /tmp/build-results/test-report.html -out_summary /tmp/build-results/test-summary.json
          go-cover-treemap -h 1080 -w 1980 -coverprofile=/tmp/build-results/cover.out > /tmp/build-results/cover-treemap.svg

      - name: Build demo command
        run: |
          CGO_ENABLED=0 go build -v
          /tmp/gsa ./demo --hide-progress --format=html -o /tmp/build-results/demo-size-analysis.html
        working-directory: ./cmd/demo

      - name: Upload demo command
        uses: actions/upload-artifact@v4
        with:
          name: demo
          path: cmd/demo/demo

      - name: Upload build results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-results
          path: /tmp/build-results

      - name: Build aws lambda handler
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -tags lambda.norpc -o bootstrap
        working-directory: ./cmd/demo-aws-lambda

      - name: Create zip for lambda deployment
        run: zip demo-aws-lambda.zip ./bootstrap ./env.txt
        working-directory: ./cmd/demo-aws-lambda

      - name: Authenticate AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-central-1

      - name: Update AWS lambda function code
        run: |
          aws lambda update-function-code  --function-name=demo-app-apiv1 --zip-file=fileb://demo-aws-lambda.zip
          aws lambda get-function-url-config --function-name demo-app-apiv1 | jq ".FunctionUrl"
        working-directory: ./cmd/demo-aws-lambda

      - name: Create AWS lambda artifact
        uses: actions/upload-artifact@v4
        with:
          name: demo-aws-lambda-wrapper
          path: cmd/demo-aws-lambda/demo-aws-lambda.zip
